Практика 6
Itsjustviktor/CoollITActivity pull request #12
Opened 2021-05-11 13:32 UTC by Itsjustviktor

Выполнил Макаров Виктор

2021-05-11 13:39 UTC, saakiys requested changes

2021-05-19 11:38 UTC, stanislavlyalin requested changes

2021-05-19 11:38 UTC, stanislavlyalin commented on pract6.py
> +    print('Сжатие выполнено')
Выводите путь к сохранённому файлу

2021-05-19 11:38 UTC, stanislavlyalin commented on pract6.py
> +        predicted_blue[i] = lm.predict(X)
Дублирование. Повторяющиеся участки кода вынесите в функцию

2021-05-20 09:25 UTC, merged