Практика 8
Itsjustviktor/CoollITActivity pull request #13
Opened 2021-05-11 13:34 UTC by Itsjustviktor

Выполнил Макаров Виктор

2021-05-11 13:39 UTC, saakiys requested changes

2021-05-11 13:39 UTC, saakiys commented on main.py
> +        print(inp + " выражение подходит" if result else inp + " выражение не подходит")
Проверено.

2021-05-19 12:07 UTC, stanislavlyalin requested changes

2021-05-19 12:07 UTC, stanislavlyalin commented on main.py
> +print("Регулярная функция для имени файла: ^[a-zA-Z0-9]*[.](png|jpeg|jpg|gif)")
* Дефисы (`-`) и подчёркивания (`_`) тоже допустимы
* Хотя бы один символ слева от точки должен быть. `*` означает 0 или более символов. Здесь уместнее `+`
* Точку лучше проверять через `\.`

2021-05-19 12:07 UTC, stanislavlyalin commented on main.py
> +print("Регулярная функция для номера телефона: ^(8|[+]7)[(](909|912|922)[)][0-9]{3}[-][0-9]{2}[-][0-9]{2}$")
Спецсимволы экранируются с помощью обратного слэша `\`

2021-05-20 09:10 UTC, stanislavlyalin requested changes

2021-05-20 09:10 UTC, stanislavlyalin commented on main.py
> +print("Регулярная функция для номера телефона: ^(8|\+7)[(](909|912|922)[)][0-9]{3}[-][0-9]{2}[-][0-9]{2}$")
Не только символ `+`, но и `(`, `)`, `-` лучше экранировать обратным слешем

2021-05-29 12:13 UTC, merged