Pract4
Itsjustviktor/CoollITActivity pull request #4
Opened 2021-03-30 17:29 UTC by saakiys

Проверяй

2021-03-30 17:33 UTC, Itsjustviktor commented on run.py
> +print("Результат: ",monkeys[object_class])
Выполнено верно
Проверил Виктор Макаров

2021-04-03 12:48 UTC, stanislavlyalin requested changes

2021-04-03 12:48 UTC, stanislavlyalin commented on run.py
> +# TODO: заполнить X данными из исследований профессора Икота.
Здесь и ниже тоже следует удалить комментарии `TODO`

2021-04-03 12:48 UTC, stanislavlyalin commented on run.py
> +from kNN import k_nearest
Не увидел файл с реализацией функции `k_nearest`

2021-04-11 07:03 UTC, merged