Практика 2 (перезалив)
Itsjustviktor/CoollITActivity pull request #7
Opened 2021-05-11 12:42 UTC by saakiys

Код ко 2 практике. 
Выполнил Саакян Саак

2021-05-11 18:27 UTC, Itsjustviktor requested changes

2021-05-17 03:37 UTC, stanislavlyalin requested changes

2021-05-17 03:37 UTC, stanislavlyalin commented on pract2/pract2.py
> +    i+=1
Лучше так:
```python
for i in range(1, 14):
    print(fibonacci(i))
```

2021-05-17 03:37 UTC, stanislavlyalin commented on pract2/pract2.py
> +        arr.append(rnd.random())
Можно упростить, используя генераторы списков:
```python
arr = [rnd.random() for i in range(n)]
return arr, (min(arr), max(arr))
```

2021-05-20 09:22 UTC, merged