Практика 3 (перезалив)
Itsjustviktor/CoollITActivity pull request #8
Opened 2021-05-11 12:49 UTC by saakiys

Выполнил Саакян Саак.
Отправлено на проверку Макарову Виктору.

2021-05-11 18:28 UTC, Itsjustviktor requested changes

2021-05-11 18:28 UTC, Itsjustviktor commented on pract3/k_means.py
> +  return centers
Проверено

2021-05-19 11:22 UTC, stanislavlyalin requested changes

2021-05-19 11:22 UTC, stanislavlyalin commented on pract3/k_means.py
> +def kmeans(k, X):
Добавьте параметр в функцию `dist_function`, передавайте его в `class_of_each_point`, а там используйте. Для примера реализуйте в `run.py` 2 функции для измерения расстояния - евклидово (как сейчас) и расстояние городских кварталов. Напишите вывод, как работает алгоритм с каждым из вариантов.

2021-05-29 12:11 UTC, merged