Практика 4 (перезалив)
Itsjustviktor/CoollITActivity pull request #9
Opened 2021-05-11 12:53 UTC by saakiys

Выполнил Саакян Саак.
Отправлено на проверку Макарову Виктору.

2021-05-11 18:29 UTC, Itsjustviktor requested changes

2021-05-11 18:29 UTC, Itsjustviktor commented on pract4/kNN.py
> +    return object_class
Проверено

2021-05-11 18:29 UTC, Itsjustviktor commented on pract4/run.py
> +monkeys = {1: 'lemur', 2: 'schimpanze', 3: 'gorilla', 4: 'orangutan'}
Проверено

2021-05-19 11:24 UTC, stanislavlyalin requested changes

2021-05-19 11:24 UTC, stanislavlyalin commented on pract4/kNN.py
> +
Отсутствует нормализация данных. Необходимо её добавить

2021-05-20 09:26 UTC, merged